spring:
  application:
    name: myITAssist
  mvc:
    async:
      request-timeout: -1
  datasource:
    url: jdbc:postgresql://localhost:5433/my-it-assist-db
    username: hermes
    password: H3rme$
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: INFO
    com.intelcia.myITAssist: DEBUG
